language: android
android:
  components:
    # Use the latest revision of Android SDK Tools
    - platform-tools
    - tools

    # The BuildTools version used by the project
    - build-tools-23.0.3

    # The SDK version used to compile the project
    - android-23

    # Extra repositories
    - extra-android-m2repository
    - extra-android-m2repository
